# Site Settings
encoding: UTF-8
exclude: ["*.gem", "*.gemspec", "Gemfile", "Gemfile.lock", "node_modules", "Rakefile", "starter-kit", "vendor"]
lang: en # Language code as defined in _data/i18n.yml. en, en-gb, en-us, zh, zh-cn, zh-tw etc.
permalink: /blog/:year/:month/:day/:title/

whitelist: [jekyll-feed, jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap]
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  auto_id_prefix: 'heading-'
  smart_quotes: ["apos", "apos", "quot", "quot"]
  toc_levels: 1..3

sass:
  style: compressed

# Site Data
title: Welcome to Siyuan Guo's tecchnical blog
description: Where tech and life growth
keywords: 'blog, life, tech'
author: Siyuan Guo
job_title: Software Engineer
location: Seattle
email: uvasiyuan@gmail.com


#social media
home:
  section1: <h1>Where tech growth</h1>
  section2: <h2>Siyuan's tech blog, Java, Interview, Distributed System, and Testing pipeline</h2>
  section3: <div class="social-links"><a class="ico-linkedin btn" href="https://www.linkedin.com/in/siyuan-guo-333387b7/" title="View on linkedin"></a></div> <div class="social-links"><a class="ico-github btn" href="https://github.com/Taitanguo" title="View on github"></a></div>

# blog:
#   cc_license: http://creativecommons.org/licenses/by-sa/4.0/ # A link to CC License of your choice.
#   cc_license_image: /assets/images/theme/cc-by-sa.png # An image of your CC License.
#   footer_content: Just for pure sharing and growth.

disqus:
  shortname: # e.g. yizeng
  public_key: # e.g. ULZ0b9TFefCUJHKQd4JCKv2v3u27YoG7YG8zXPewkWrT333Z0Se9YnxLzoV6VM8W
google_analytics: # e.g. 'UA-42456515-5'
addthis_public_id: # AddThis sharing plugin. See http://www.addthis.com/. E.g. ra-53329e27694534j5

paths:
  home: /
  blog: /blog/
  categories: /blog/categories/
  tags: /blog/tags/
